### ISSUE TITLE
Cant craft nor see how to craft

### ISSUE THREAD

**Issue by cheesepufftyler** [TheBusyBiscuit/ExtraGear#6]
Will not pull up how to craft it and even by googling how to, it still dont do anything.

Slimefun4-125
ExtraGear_v1.1.1

**Comment by LinoxGH** [comment]
@cheesepufftyler it'd be a lot better if you give us more info such as:
- Does this still happen in Build #207 of Slimefun4.
- What item are you trying to craft.
- "it still dont do anything" what the word "it" takes place of.
